// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package ola.rpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ola.rpc.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 1;</code>
     */
    REQUEST(0, 1),
    /**
     * <code>RESPONSE = 2;</code>
     */
    RESPONSE(1, 2),
    /**
     * <code>RESPONSE_CANCEL = 3;</code>
     */
    RESPONSE_CANCEL(2, 3),
    /**
     * <code>RESPONSE_FAILED = 4;</code>
     */
    RESPONSE_FAILED(3, 4),
    /**
     * <code>RESPONSE_NOT_IMPLEMENTED = 5;</code>
     */
    RESPONSE_NOT_IMPLEMENTED(4, 5),
    /**
     * <code>DISCONNECT = 6;</code>
     */
    DISCONNECT(5, 6),
    /**
     * <code>DESCRIPTOR_REQUEST = 7;</code>
     *
     * <pre>
     * not implemented
     * </pre>
     */
    DESCRIPTOR_REQUEST(6, 7),
    /**
     * <code>DESCRIPTOR_RESPONSE = 8;</code>
     *
     * <pre>
     * not implemented
     * </pre>
     */
    DESCRIPTOR_RESPONSE(7, 8),
    /**
     * <code>REQUEST_CANCEL = 9;</code>
     */
    REQUEST_CANCEL(8, 9),
    /**
     * <code>STREAM_REQUEST = 10;</code>
     *
     * <pre>
     * a request that we don't expect a response for
     * </pre>
     */
    STREAM_REQUEST(9, 10),
    ;

    /**
     * <code>REQUEST = 1;</code>
     */
    public static final int REQUEST_VALUE = 1;
    /**
     * <code>RESPONSE = 2;</code>
     */
    public static final int RESPONSE_VALUE = 2;
    /**
     * <code>RESPONSE_CANCEL = 3;</code>
     */
    public static final int RESPONSE_CANCEL_VALUE = 3;
    /**
     * <code>RESPONSE_FAILED = 4;</code>
     */
    public static final int RESPONSE_FAILED_VALUE = 4;
    /**
     * <code>RESPONSE_NOT_IMPLEMENTED = 5;</code>
     */
    public static final int RESPONSE_NOT_IMPLEMENTED_VALUE = 5;
    /**
     * <code>DISCONNECT = 6;</code>
     */
    public static final int DISCONNECT_VALUE = 6;
    /**
     * <code>DESCRIPTOR_REQUEST = 7;</code>
     *
     * <pre>
     * not implemented
     * </pre>
     */
    public static final int DESCRIPTOR_REQUEST_VALUE = 7;
    /**
     * <code>DESCRIPTOR_RESPONSE = 8;</code>
     *
     * <pre>
     * not implemented
     * </pre>
     */
    public static final int DESCRIPTOR_RESPONSE_VALUE = 8;
    /**
     * <code>REQUEST_CANCEL = 9;</code>
     */
    public static final int REQUEST_CANCEL_VALUE = 9;
    /**
     * <code>STREAM_REQUEST = 10;</code>
     *
     * <pre>
     * a request that we don't expect a response for
     * </pre>
     */
    public static final int STREAM_REQUEST_VALUE = 10;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return RESPONSE;
        case 3: return RESPONSE_CANCEL;
        case 4: return RESPONSE_FAILED;
        case 5: return RESPONSE_NOT_IMPLEMENTED;
        case 6: return DISCONNECT;
        case 7: return DESCRIPTOR_REQUEST;
        case 8: return DESCRIPTOR_RESPONSE;
        case 9: return REQUEST_CANCEL;
        case 10: return STREAM_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ola.rpc.Rpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ola.rpc.Type)
  }

  public interface RpcMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ola.rpc.RpcMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ola.rpc.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .ola.rpc.Type type = 1;</code>
     */
    ola.rpc.Rpc.Type getType();

    /**
     * <code>optional uint32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bytes buffer = 4;</code>
     */
    boolean hasBuffer();
    /**
     * <code>optional bytes buffer = 4;</code>
     */
    com.google.protobuf.ByteString getBuffer();
  }
  /**
   * Protobuf type {@code ola.rpc.RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ola.rpc.RpcMessage)
      RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ola.rpc.Rpc.Type value = ola.rpc.Rpc.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              buffer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ola.rpc.Rpc.RpcMessage.class, ola.rpc.Rpc.RpcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMessage> PARSER =
        new com.google.protobuf.AbstractParser<RpcMessage>() {
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ola.rpc.Rpc.Type type_;
    /**
     * <code>required .ola.rpc.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ola.rpc.Type type = 1;</code>
     */
    public ola.rpc.Rpc.Type getType() {
      return type_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional uint32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUFFER_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString buffer_;
    /**
     * <code>optional bytes buffer = 4;</code>
     */
    public boolean hasBuffer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes buffer = 4;</code>
     */
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }

    private void initFields() {
      type_ = ola.rpc.Rpc.Type.REQUEST;
      id_ = 0;
      name_ = "";
      buffer_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, buffer_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, buffer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ola.rpc.Rpc.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ola.rpc.Rpc.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ola.rpc.Rpc.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ola.rpc.Rpc.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ola.rpc.RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ola.rpc.RpcMessage)
        ola.rpc.Rpc.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ola.rpc.Rpc.RpcMessage.class, ola.rpc.Rpc.RpcMessage.Builder.class);
      }

      // Construct using ola.rpc.Rpc.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = ola.rpc.Rpc.Type.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        buffer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ola.rpc.Rpc.internal_static_ola_rpc_RpcMessage_descriptor;
      }

      public ola.rpc.Rpc.RpcMessage getDefaultInstanceForType() {
        return ola.rpc.Rpc.RpcMessage.getDefaultInstance();
      }

      public ola.rpc.Rpc.RpcMessage build() {
        ola.rpc.Rpc.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ola.rpc.Rpc.RpcMessage buildPartial() {
        ola.rpc.Rpc.RpcMessage result = new ola.rpc.Rpc.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.buffer_ = buffer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ola.rpc.Rpc.RpcMessage) {
          return mergeFrom((ola.rpc.Rpc.RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ola.rpc.Rpc.RpcMessage other) {
        if (other == ola.rpc.Rpc.RpcMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasBuffer()) {
          setBuffer(other.getBuffer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ola.rpc.Rpc.RpcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ola.rpc.Rpc.RpcMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ola.rpc.Rpc.Type type_ = ola.rpc.Rpc.Type.REQUEST;
      /**
       * <code>required .ola.rpc.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ola.rpc.Type type = 1;</code>
       */
      public ola.rpc.Rpc.Type getType() {
        return type_;
      }
      /**
       * <code>required .ola.rpc.Type type = 1;</code>
       */
      public Builder setType(ola.rpc.Rpc.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ola.rpc.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ola.rpc.Rpc.Type.REQUEST;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes buffer = 4;</code>
       */
      public boolean hasBuffer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes buffer = 4;</code>
       */
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }
      /**
       * <code>optional bytes buffer = 4;</code>
       */
      public Builder setBuffer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        buffer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes buffer = 4;</code>
       */
      public Builder clearBuffer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buffer_ = getDefaultInstance().getBuffer();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ola.rpc.RpcMessage)
    }

    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ola.rpc.RpcMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ola_rpc_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ola_rpc_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRpc.proto\022\007ola.rpc\"S\n\nRpcMessage\022\033\n\004ty" +
      "pe\030\001 \002(\0162\r.ola.rpc.Type\022\n\n\002id\030\002 \001(\r\022\014\n\004n" +
      "ame\030\003 \001(\t\022\016\n\006buffer\030\004 \001(\014*\322\001\n\004Type\022\013\n\007RE" +
      "QUEST\020\001\022\014\n\010RESPONSE\020\002\022\023\n\017RESPONSE_CANCEL" +
      "\020\003\022\023\n\017RESPONSE_FAILED\020\004\022\034\n\030RESPONSE_NOT_" +
      "IMPLEMENTED\020\005\022\016\n\nDISCONNECT\020\006\022\026\n\022DESCRIP" +
      "TOR_REQUEST\020\007\022\027\n\023DESCRIPTOR_RESPONSE\020\010\022\022" +
      "\n\016REQUEST_CANCEL\020\t\022\022\n\016STREAM_REQUEST\020\n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ola_rpc_RpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ola_rpc_RpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ola_rpc_RpcMessage_descriptor,
        new java.lang.String[] { "Type", "Id", "Name", "Buffer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
